close all;
clc;
% 
% % clear all;
% % figure(1);
% % load("Lab7_3.mat"); %10rpm_5ms
% % t = 0:BTI:1999*BTI;
% % subplot(2,1,1);
% % plot(t, vel*60/2/pi);
% % xlabel("Time (s)");
% % ylabel("RPM");
% % title("10rpm 5ms KP="+KP+" KI="+KI);
% % ylim([-5, 40]);
% % subplot(2,1,2);
% % Km = 0.00583;
% % Ka = 8;
% % i = volt*Ka;
% % v = Km*vel;
% % p = i.*v;
% % plot(t, p);
% % ylabel("Power (W)");
% 
% clear all;
% figure(2);
% load("Lab7_4.mat"); %10rpm_20ms
% t = 0:BTI:4999*BTI;
% subplot(2,1,1);
% plot(t, vel*60/2/pi);
% xlim([0, 60]);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+KP+" KI="+KI);
% ylim([-5, 40]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = volt*Ka;
% v = Km*vel;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([0, 60]);
% 
% % clear all;
% % figure(3);
% % load("Lab7_60rpm_5ms.mat"); %60rpm_5ms
% % t = 0:BTI:4999*BTI;
% % subplot(2,1,1);
% % plot(t, vel*60/2/pi);
% % xlabel("Time (s)");
% % ylabel("RPM");
% % title("60rpm 5ms KP="+KP+" KI="+KI);
% % xlim([0, 5]);
% % ylim([0, 100]);
% % subplot(2,1,2);
% % Km = 0.00583;
% % Ka = 8;
% % i = volt*Ka;
% % v = Km*vel;
% % p = i.*v;
% % plot(t, p);
% % ylabel("Power (W)");
% 
% 
% clear all;
% figure(4);
% load("Lab7_60rpm_20ms.mat"); %60rpm_20ms
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, vel*60/2/pi);
% xlabel("Time (s)");
% ylabel("RPM");
% title("60rpm 20ms KP="+KP+" KI="+KI);
% xlim([0, 5]);
% ylim([0, 100]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = volt*Ka;
% v = Km*vel;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([0, 5]);
% 
% clear all;
% figure(5);
% load("Lab7_10rpm_20ms_2x.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, vel*60/2/pi);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+KP+" KI="+KI);
% ylim([-5, 40]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = volt*Ka;
% v = Km*vel;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% 
% % clear all;
% % figure(6);
% % load("Lab7_10rpm_5ms_2x.mat"); 
% % t = 0:BTI:1999*BTI;
% % subplot(2,1,1);
% % plot(t, vel*60/2/pi);
% % xlabel("Time (s)");
% % ylabel("RPM");
% % title("10rpm 5ms KP="+KP+" KI="+KI);
% % ylim([-5, 40]);
% % subplot(2,1,2);
% % Km = 0.00583;
% % Ka = 8;
% % i = volt*Ka;
% % v = Km*vel;
% % p = i.*v;
% % plot(t, p);
% % ylabel("Power (W)");
% 
% % clear all;
% % figure(7);
% % load("Lab7_1rpm_20ms_2x.mat"); 
% % t = 0:BTI:1999*BTI;
% % subplot(2,1,1);
% % plot(t, vel*60/2/pi);
% % xlabel("Time (s)");
% % ylabel("RPM");
% % title("1rpm 20ms KP="+KP+" KI="+KI);
% % ylim([-5, 40]);
% % subplot(2,1,2);
% % Km = 0.00583;
% % Ka = 8;
% % i = volt*Ka;
% % v = Km*vel;
% % p = i.*v;
% % plot(t, p);
% % ylabel("Power (W)");
% 
% % clear all;
% % figure(8);
% % load("Lab7_5rpm_20ms_2x.mat"); 
% % t = 0:BTI:1999*BTI;
% % subplot(2,1,1);
% % plot(t, vel*60/2/pi);
% % xlabel("Time (s)");
% % ylabel("RPM");
% % title("5rpm 20ms KP="+KP+" KI="+KI);
% % ylim([-5, 40]);
% % subplot(2,1,2);
% % Km = 0.00583;
% % Ka = 8;
% % i = volt*Ka;
% % v = Km*vel;
% % p = i.*v;
% % plot(t, p);
% % ylabel("Power (W)");
% 
% clear all;
% figure(9);
% load("Lab7_60rpm_20ms_2x.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, vel*60/2/pi);
% xlabel("Time (s)");
% ylabel("RPM");
% title("60rpm 20ms KP="+KP+" KI="+KI);
% xlim([0,5]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = volt*Ka;
% v = Km*vel;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([0,5]);
% 
% clear all;
% figure(10);
% load("Vel_trial.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% ylim([-5, 40]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = Km*wrpm_trans*2*pi/60;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% 
% clear all;
% figure(11);
% load("Vel_trial1.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% ylim([-5, 40]);
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = Km*wrpm_trans*2*pi/60;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% 
% clear all;
% figure(11);
% load("Vel_trial2.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlim([0, 5]);
% xlabel("Time (s)");
% ylabel("RPM");
% title("60rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = Km*wrpm_trans*2*pi/60;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([0,5]);
% 
% clear all;
% figure(12);
% load("Vel_trial3.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlim([5, 10]);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = Km*wrpm_trans*2*pi/60;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([5,10]);
% 
% clear all;
% figure(12);
% load("Vel_in_off.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlim([5, 10]);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = Km*wrpm_trans*2*pi/60;
% p = i.*v;
% plot(t, p);
% ylabel("Power (W)");
% xlim([5,10]);
% 
% clear all;
% figure(13);
% load("Vel_inout_off.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(2,1,1);
% plot(t, wrpm_trans);
% xlim([5, 10]);
% xlabel("Time (s)");
% ylabel("RPM");
% title("10rpm 20ms KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(2,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = -Km*wrpm_trans*2*pi/60;
% T=i*Ka*Km;
% p = i.*v;
% plot(t, T);
% ylabel("Power (W)");
% xlim([5,10]);

% clear all;
% figure(14);
% load("Test1.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(3,1,1);
% plot(t, wrpm_trans);
% xlim([5, 11]);
% grid on;
% xlabel("Time (s)");
% ylabel("RPM");
% title(targetvel+"rpm KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(3,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = -Km*wrpm_trans*2*pi/60;
% T=i*Ka*Km;
% p = i.*v;
% plot(t, T);
% ylabel("Torque (N*m)");
% xlim([5,11]);
% grid on;
% subplot(3,1,3);
% plot(t,p); 
% ylabel("Power (W)");
% xlim([5,11]);
% grid on;
% 
% clear all;
% figure(15);
% load("Test2.mat"); 
% t = 0:BTI:1999*BTI;
% subplot(3,1,1);
% plot(t, wrpm_trans);
% xlim([5, 11]);
% grid on;
% xlabel("Time (s)");
% ylabel("RPM");
% title(targetvel+"rpm KP="+kp_ss(1)+" KI="+ki_ss(1));
% subplot(3,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = -Km*wrpm_trans*2*pi/60;
% T=i*Ka*Km;
% p = i.*v;
% plot(t, T);
% ylabel("Torque (N*m)");
% xlim([5,11]);
% grid on;
% subplot(3,1,3);
% plot(t,p); 
% ylabel("Power (W)");
% xlim([5,11]);
% grid on;
% 
% clear all;
% figure(16);
% load("Test3.mat"); 
% t = 0:BTI:4999*BTI;
% subplot(3,1,1);
% plot(t, wrpm_trans);
% grid on;
% xlabel("Time (s)");
% ylabel("RPM");
% title(targetvel+"rpm KP="+kp_trans(1)+" KI="+ki_trans(1));
% subplot(3,1,2);
% Km = 0.00583;
% Ka = 8;
% i = Amp_trans;
% v = -Km*wrpm_trans*2*pi/60;
% T=i*Ka*Km;
% p = i.*v;
% plot(t, T);
% ylabel("Torque (N*m)");
% grid on;
% subplot(3,1,3);
% plot(t,p); 
% ylabel("Power (W)");
% grid on;

clear all;
figure(16);
load("test_60rpm.mat"); 
t = 0:BTI:4999*BTI;
subplot(3,1,1);
plot(t, wrpm_ss);
grid on;
xlabel("Time (s)");
ylabel("RPM");
title(targetvel+"rpm KP="+kp_trans(1)+" KI="+ki_trans(1));
subplot(3,1,2);
Km = 0.00583;
Ka = 8;
i = Amp_trans;
v = -Km*wrpm_trans*2*pi/60;
T=i*Ka*Km;
p = i.*v;
plot(t, T);
ylabel("Torque (N*m)");
grid on;
subplot(3,1,3);
plot(t,p); 
ylabel("Power (W)");
grid on;